"""empty message

Revision ID: e742e19992a8
Revises: 
Create Date: 2020-03-14 14:57:14.325333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e742e19992a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('longhash', sa.String(length=256), nullable=False),
    sa.Column('shorthash', sa.String(length=9), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('longhash'),
    sa.UniqueConstraint('shorthash'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link')
    # ### end Alembic commands ###
